# Generated by Django 4.0.1 on 2022-01-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboard', '0004_rename_isaccepted_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
