# Generated by Django 4.0.1 on 2022-01-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theboard', '0007_alter_userprofile_news_susbscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='news_susbscribed',
            field=models.BooleanField(default=False, verbose_name='Newsletter subscription'),
        ),
    ]
